### ISSUE TITLE
Strings in mail templates not extracted

### ISSUE THREAD

**Issue by wordish** [mlocati/concrete5-translate-library#13]
* fresh install of 8.5.7
* install another locale
* go to Translate Site Interface
* reload strings
* edit the strings for the locale
* search for a string from one of the mail templates, such as "Dear "
* no strings show up in the results
* Note: copy a file from `/concrete/mail` to `/application/mail` and the strings _will_ show up after reloading the strings.

![Screenshot from 2022-05-12 14-27-00](https://user-images.githubusercontent.com/42463480/168170922-437606d1-77d7-453a-acd4-c38ea3ccd582.png)

`/concrete/mail/forgot_password.php`:

```
$body = t("

Dear %s,

You have requested a new password for the site %s 

Your username is: %s

You may change your password at the following address:

%s

Thanks for browsing the site!

", $uName, $siteName, $uName, $changePassURL);
```

![Screenshot from 2022-05-12 14-29-56](https://user-images.githubusercontent.com/42463480/168171293-751a731f-e453-4981-8a5b-69776f9f2b4e.png)

**Comment by mlocati** [comment]
The translatable strings under the `/concrete` directory aren't extracted by `Translate Site Interface`.
This occurs for the files in the `concrete/mail` folder, as well as for everything else (for example, the core dashboard pages).

Since those are "core" strings, they are extracted by https://translate.concretecms.org and you can translate them in that website.

For example, we have that the `concrete/mail/basic_workflow_notification.php` file contains this text:

```php
<?php

defined('C5_EXECUTE') or die("Access Denied.");

$subject = $siteName . " " . t("Workflow Notification");
$body = t("Dear %s,

%s

You can review, approve or deny all pending actions from here:

%s
", $uName, $message, URL::to('/dashboard/welcome/me'));
```

and in the https://translate.concretecms.org we actually have this string:

![immagine](https://user-images.githubusercontent.com/928116/168326445-81a9b386-a65f-4b65-aeec-9e94e7d1dc89.png)

Why people can't translate the core stuff in their `Translate Site Interface`? Because the core contains thousands of translatable strings (6,884 for v8, 7,747 for v9), and managing them (and finding the non-core ones) would be a nightmare.

If the problem is that people don't have a core translation string that's translated, they can do that in the https://translate.concretecms.org website, then they can update the core translations by using the "Update languages" page that's available in the dashboard page of the installed instance.
